version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - source config/variables.env
      - chmod +x scripts/*.sh

      - echo "Looking up latest Amazon Linux 2023 x86_64 AMI..."
      - >
        BASE_AMI_ID="$(aws ec2 describe-images
        --region "$AWS_REGION"
        --owners "$BASE_AMI_OWNER"
        --filters "Name=name,Values=$BASE_AMI_NAME_PATTERN" "Name=state,Values=available"
        --query "Images | sort_by(@, &CreationDate) | [-1].ImageId"
        --output text)"
      - echo "Using BASE_AMI_ID=$BASE_AMI_ID"

      - BUILD_TS="$(date +%Y%m%d-%H%M%S)"
      - AMI_NAME="${AMI_NAME_PREFIX}-${BUILD_TS}"
      - echo "AMI_NAME=${AMI_NAME}"
      - |
        if [[ "${INSTANCE_PROFILE_NAME}" == arn:* ]]; then
          IAM_INSTANCE_PROFILE="Arn=${INSTANCE_PROFILE_NAME}"
        else
          IAM_INSTANCE_PROFILE="Name=${INSTANCE_PROFILE_NAME}"
        fi
        echo "IAM_INSTANCE_PROFILE=${IAM_INSTANCE_PROFILE}"

  build:
    commands:
      - set -euo pipefail

      - echo "1) Launch builder instance"
      - >
        BUILDER_INSTANCE_ID="$(aws ec2 run-instances
        --region "$AWS_REGION"
        --image-id "$BASE_AMI_ID"
        --instance-type "$INSTANCE_TYPE"
        --subnet-id "$SUBNET_ID"
        --security-group-ids "$SECURITY_GROUP_ID"
        --iam-instance-profile "$IAM_INSTANCE_PROFILE"
        --tag-specifications "ResourceType=instance,Tags=[{Key=Purpose,Value=GoldenAMIBuilder},{Key=Project,Value=$PROJECT_TAG}]"
        --query "Instances[0].InstanceId"
        --output text)"
      - echo "BUILDER_INSTANCE_ID=$BUILDER_INSTANCE_ID"

      - echo "Waiting for instance to be running..."
      - aws ec2 wait instance-running --region "$AWS_REGION" --instance-ids "$BUILDER_INSTANCE_ID"

      - echo "Waiting for SSM to be Online..."
      - scripts/wait_for_ssm.sh "$BUILDER_INSTANCE_ID" 420 "$AWS_REGION"

      - echo "2) Patch/configure builder"
      - PATCH_B64="$(base64 scripts/patch_and_configure.sh | tr -d '\n')"
      - >
        PATCH_COMMAND_ID="$(aws ssm send-command
        --region "$AWS_REGION"
        --document-name "AWS-RunShellScript"
        --targets "Key=instanceids,Values=$BUILDER_INSTANCE_ID"
        --parameters commands="[
          \"set -euo pipefail\",
          \"echo '$PATCH_B64' | base64 -d | sudo tee /tmp/patch_and_configure.sh >/dev/null\",
          \"sudo chmod +x /tmp/patch_and_configure.sh\",
          \"sudo /tmp/patch_and_configure.sh\"
        ]"
        --query "Command.CommandId"
        --output text)"
      - echo "PATCH_COMMAND_ID=$PATCH_COMMAND_ID"

      - echo "Waiting for patch/configure SSM command to complete..."
      - |
        while true; do
          STATUS=$(aws ssm get-command-invocation \
            --region "$AWS_REGION" \
            --command-id "$PATCH_COMMAND_ID" \
            --instance-id "$BUILDER_INSTANCE_ID" \
            --query "Status" \
            --output text)

          echo "SSM Status: $STATUS"

          if [[ "$STATUS" == "Success" ]]; then
            break
          elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
            echo "SSM command failed. Full invocation output:"
            aws ssm get-command-invocation \
              --region "$AWS_REGION" \
              --command-id "$PATCH_COMMAND_ID" \
              --instance-id "$BUILDER_INSTANCE_ID"
            exit 1
          fi

          sleep 10
        done

      - echo "3) Create AMI"
      - >
        AMI_ID="$(aws ec2 create-image
        --region "$AWS_REGION"
        --instance-id "$BUILDER_INSTANCE_ID"
        --name "$AMI_NAME"
        --no-reboot
        --tag-specifications "ResourceType=image,Tags=[{Key=Purpose,Value=GoldenAMI},{Key=Project,Value=$PROJECT_TAG}]"
        --query "ImageId"
        --output text)"
      - echo "AMI_ID=$AMI_ID"

      - echo "Waiting for AMI to become available..."
      - aws ec2 wait image-available --region "$AWS_REGION" --image-ids "$AMI_ID"

      - echo "Writing ami_id.txt"
      - echo "$AMI_ID" > ami_id.txt

  post_build:
    commands:
      - set -euo pipefail
      - echo "Cleanup builder instance"
      - scripts/cleanup.sh "$AWS_REGION" "${BUILDER_INSTANCE_ID:-}" ""

artifacts:
  files:
    - ami_id.txt
    - buildspec/**/*
    - scripts/**/*
    - config/**/*
